### ISSUE TITLE
Gradle 5 NoClassDefFoundError ClosureBackedAction

### ISSUE THREAD

**Issue by geoHeil** [spotbugs/spotbugs-gradle-plugin#72]
Using SpotBugs 1.6.5 I get:

`NoClassDefFoundError: org/gradle/api/internal/ClosureBackedAction`

for:
```
tasks.withType(com.github.spotbugs.SpotBugsTask) {
        reports {
            xml.enabled = false
            html.enabled = true
        }
    }
```

**Comment by ragnor** [comment]
@geoHeil How did you resolve it? I have the same error after migration from gradle 4.9 to 5.1
